openapi: 3.0.1
info:
  description: The realtime protocol for the template match engine.
  title: xoxoapi.proto
  version: version not set
servers:
- url: /
paths: {}
components:
  schemas:
    protobufAny:
      properties:
        type_url:
          type: string
        value:
          format: byte
          pattern: "^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$"
          type: string
      type: object
    runtimeError:
      properties:
        error:
          type: string
        code:
          format: int32
          type: integer
        message:
          type: string
        details:
          items:
            $ref: '#/components/schemas/protobufAny'
          type: array
      type: object
x-original-swagger-version: "2.0"
