/*
 * xoxoapi.proto
 *
 * The realtime protocol for the template match engine.
 *
 * API version: version not set
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ProtobufAny struct {

	TypeUrl string `json:"type_url,omitempty"`

	Value string `json:"value,omitempty" validate:"regexp=^(?:[A-Za-z0-9+\\/]{4})*(?:[A-Za-z0-9+\\/]{2}==|[A-Za-z0-9+\\/]{3}=)?$"`
}
