name: Trigger Backend Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dispatch:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger ToDoApp-backend Workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          repository: Mohammed-Alhuraibi/ToDoApp-backend
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: trigger-backend
